tty: true
driver:
  kind: modern_ebpf
collectors:
  containerd:
    socket: /run/k3s/containerd/containerd.sock
falco:
  rules_files:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/rules.d
image:
  registry: docker.io
  repository: falcosecurity/falco-no-driver
  tag: "0.38.2"
metrics:
  # -- enabled specifies whether the metrics should be enabled.
  enabled: false
  interval: 1h
falcoctl:
  image:
    registry: docker.io
    repository: falcosecurity/falcoctl
    tag: "0.9.0"

falcosidekick:
  enabled: true
  replicaCount: 1
  webui:
    replicaCount: 1
    enabled: true
    user: "admin:admin"
    disableauth: false
    image:
      registry: docker.io
      repository: falcosecurity/falcosidekick-ui
      tag: "2.2.0"
  image:
    registry: docker.io
    repository: falcosecurity/falcosidekick
    tag: 2.29.0
  config:
    slack:
      webhookurl: "" # -- if not empty, Webhook output is *enabled*
      channel: ""
    webhook:
      address: "" # -- if not empty, Webhook output is *enabled*
      method: "POST"
      customHeaders: "" # -- a list of comma separated custom headers to add, syntax is "key:value\,key:value"
    discord:
      webhookurl: "" # -- if not empty, Discord output is *enabled*



